### ISSUE TITLE
Allow verbose mode

### ISSUE THREAD

**Issue by mightyiam** [dustinblackman/cargo-run-bin#2]
I'm not sure that the default silence is really what I desire. Perhaps verbosity should be the default. In any case, at least allowed. You know, builds can fail. It happened to me just know, trying to use `cargo bin makers`. It's from the crate `cargo-make` which failed to build because of missing native dependencies. But I had to guess that and try to install it using good old `cargo install`, to find out why it's not compiling.

**Comment by dustinblackman** [comment]
Fixed in [v1.0.0](https://github.com/dustinblackman/cargo-run-bin/releases/tag/v1.0.0). Thanks for the recommendation!

**Comment by mightyiam** [comment]
Thank you!
