### ISSUE TITLE
shims are invalid when `$SHELL` is not posix-compliant

### ISSUE THREAD

**Issue by sharnoff** [dustinblackman/cargo-run-bin#24]
Hi!

I typically use fish as my shell. If `cargo bin --install` is run with the `SHELL` environment variable set to `fish`, later attempts to run with `cargo bin <binary>` shim emit warnings like:

```
/path/to/.bin/.shims/<binary> (line 3): Missing end to balance this if statement
if [ ! -t 0 ]; then
^^
warning: Error while reading file /path/to/.bin/.shims/<binary>
```

because the shim has `#!/usr/bin/env fish`.

---

I had a brief look at the code -- is there a reason why `cargo-run-bin` can't just always use `#!/usr/bin/env sh`?

**Comment by dustinblackman** [comment]
Hey there! Thanks for the report.

I have some memory that some sub-process of a sub-process through shims was losing environment variables when I was first putting this together, but am not recalling which. Either way, you're still correct! The tool should handle this. It's been patched in https://github.com/dustinblackman/cargo-run-bin/releases/tag/v1.7.3

Thanks!

**Comment by sharnoff** [comment]
Awesome, thanks!
