### ISSUE TITLE
version of cargo_toml dependency has been yanked

### ISSUE THREAD

**Issue by mightyiam** [dustinblackman/cargo-run-bin#5]
https://github.com/dustinblackman/cargo-run-bin/blob/b5388e33b000d54444fa5213472546eb3164872d/Cargo.toml#L19

This crate no longer compiles, due to unobtainable dependency, `cargo_toml@^0.9`.

Could you please update the dependency, @dustinblackman ? Alternatively, would you mind a PR that does so?

**Comment by dustinblackman** [comment]
Fixed in https://github.com/dustinblackman/cargo-run-bin/commit/b81dcd607089b05eb939e915514334b070a4bb35, thanks for letting me know!

**Comment by mightyiam** [comment]
Thank you!
