### ISSUE TITLE
use `cargo-binstall` to download precompiled binaries

### ISSUE THREAD

**Issue by ForsakenHarmony** [dustinblackman/cargo-run-bin#6]
https://github.com/cargo-bins/cargo-binstall

(also add binaries to the releases to be able to binstall `cargo-run-bin`)

**Comment by dustinblackman** [comment]
Both of these ideas are great! I considered bundling in binstall, but our licenses conflict. I've found a nice solution that allows you to install `cargo-binstall` either globally or through `cargo-run-bin` and it'll work as expected. :D It'll be available in the next release.

https://github.com/dustinblackman/cargo-run-bin/commit/ced06305199c2a47b3465ba23efeeccfd9dfb722
