### ISSUE TITLE
Fails when no `package.version`

### ISSUE THREAD

**Issue by mightyiam** [dustinblackman/cargo-run-bin#8]
I'm running cargo-run-bin at the root of a workspace, where the version is not specified as `package.version` but as `workspace.package.version`. And I'm getting

```
run-bin failed: missing field `version` for key `package` at line 51 column 1
```

**Comment by mightyiam** [comment]
https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

**Comment by dustinblackman** [comment]
Good call out, there's no proper support for workspaces. Are you defining binaries in your individual crates Cargo.toml, or the workspaces Cargo.toml?

I'd assume the workspace Cargo.toml is the correct spot.

**Comment by mightyiam** [comment]
I'm defining binaries in the workspace Cargo.toml.

**Comment by dustinblackman** [comment]
Fixed in https://github.com/dustinblackman/cargo-run-bin/commit/208b000f47ee7666009a066a9f2a5124275ea381

Thanks!

**Comment by mightyiam** [comment]
Dustin, kudos on the response time. And thank you!
