### ISSUE TITLE
Support git and path as source

### ISSUE THREAD

**Issue by alexkazik** [dustinblackman/cargo-run-bin#9]
[Cargo install](https://doc.rust-lang.org/cargo/commands/cargo-install.html) does support the same options as depencies: git (optionally with branch, tag and rev) and path. It would be great if that is also supported to help local development.

But in that cases binstall can't be used (as only those in crates.io are available).

Though I don't know if it should be possible to specify version and git/path. For dependencies the git/path part is removed on publish but that does probably not happen for this. First option: do not allow multiple, second option: try git/path, if not available use version. (I think that's it always an error to use git and path.)

I can try to create a PR if that is something which is desirable.

**Comment by dustinblackman** [comment]
Git support added in https://github.com/dustinblackman/cargo-run-bin/pull/10

@alexkazik You're welcome to add `path` if you'd like to contribute, otherwise I may get some free time next week.
